### ISSUE TITLE
: cannot connect to X server - Kaggle?

### ISSUE THREAD

**Issue by CurtisASmith** [eps696/aphantasia#10]
I am unsuccessfully trying to run clip_fft.py in a Kaggle [notebook](https://www.kaggle.com/curtisasmith/clip-fft). The error message is seen below:
```
Start...
/kaggle/working/aphantasia/clip_fft.py:128: UserWarning: The function torch.irfft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.ifft or torch.fft.irfft. (Triggered internally at  /pytorch/aten/src/ATen/native/SpectralOps.cpp:602.)
  image = torch.irfft(scaled_spectrum_t, 2, normalized=True, signal_sizes=(h, w))
: cannot connect to X server 
```
Previously I had errors that seemed to stem from dependencies, which I resolved. However, `: cannot connect to X server` is a dead end to me, although apparently it has something to do with displays. The last thing I tried was turning off `verbose`, thinking that displaying the previews may be the problem, but this did not solve the issue. I have no idea where to begin troubleshooting further. In fact, I'm not even sure if the issue is rooted in this tool, or in Kaggle. This tool works fine in the intended Colab environment*, and I'm not sure if you (eps696) have used Kaggle, so I understand if this issue is out of scope. Nonetheless I would appreciate any insight you or others might have!

*except that I keep running out of GPU time - Kaggle displays the time limits, at least

**Comment by eps696** [comment]
my first (and only) guess is about cv2 preview as well (switch off `verbose`); apart from that, there should be no other windowed graphics use. try to comment out (or remove) all mentioning of `cvshow` function (and maybe `cv2` module import) to see if it helps. 
alas, i never used kaggle, so not sure if can assist more than that

**Comment by eps696** [comment]
closing for now; feel free to reopen, if new info/questions arise
