### ISSUE TITLE
New error with previous aphantasia versions

### ISSUE THREAD

**Issue by smithee77** [eps696/aphantasia#12]
Hi, first of thanks for your code and congrats for this amazing tool.
I have some customised versions of aphantasia, starting from your previous colab versions. They worked fine, but now when I try to run them I get the error below. Is this a bug? Or those versions are no longer usable with the library now? Is there a way of making them work again :)?  
Thanks again

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-20b66e66c4ad> in <module>()
     58 get_ipython().system('git clone https://github.com/eps696/aphantasia')
     59 get_ipython().magic('cd /content/aphantasia/')
---> 60 from clip_fft import to_valid_rgb, fft_image, slice_imgs, checkout
     61 from utils import pad_up_to, basename, img_list, img_read
     62 from progress_bar import ProgressIPy as ProgressBar

/content/aphantasia/clip_fft.py in <module>()
     15 import clip
     16 os.environ['KMP_DUPLICATE_LIB_OK']='True'
---> 17 from sentence_transformers import SentenceTransformer
     18 import pytorch_ssim as ssim
     19 

ModuleNotFoundError: No module named 'sentence_transformers'

--------------------------------------------------------------------------

**Comment by eps696** [comment]
thanks for your interest; glad that it's helpful. 
alas, i cannot guarantee compatibility between github repo and any other preliminary versions; there were quite a few breaking changes indeed. 
as for your specific error - whenever you see `ModuleNotFoundError: No module named 'XXX'`, just run `pip install XXX`, it will solve it in 97% cases (incl. this one). for Colab you'll have to add `!pip install sentence_transformers` somewhere in General setup. 
i would suggest to move your customization to the fresh base from github tho; this is more guaranteed way to make it work again.

**Comment by smithee77** [comment]
definitely works that way! newbie error, my mistake...yeah I'll keep'em apart. Thanks again!
