### ISSUE TITLE
I have tried to use illustra in colab but it gives me the following error

### ISSUE THREAD

**Issue by raul2297** [eps696/aphantasia#21]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-f74286952387> in <module>()
     73 get_ipython().system('git clone https://github.com/eps696/aphantasia')
     74 get_ipython().magic('cd aphantasia/')
---> 75 from clip_fft import to_valid_rgb, fft_image, slice_imgs, checkout
     76 from utils import pad_up_to, basename, file_list, img_list, img_read, txt_clean, plot_text
     77 from progress_bar import ProgressIPy as ProgressBar

/content/aphantasia/clip_fft.py in <module>()
     16 os.environ['KMP_DUPLICATE_LIB_OK']='True'
     17 from sentence_transformers import SentenceTransformer
---> 18 import lpips
     19 
     20 from utils import pad_up_to, basename, img_list, img_read, plot_text, txt_clean

ModuleNotFoundError: No module named 'lpips'

**Comment by eps696** [comment]
should be fixed now

**Comment by raul2297** [comment]
Thank you very much brother. By the way, the project is incredible to me, I
do poetry and I was very interested in using illustra to bring my poems
into visual art. I am from the Dominican Republic if one day you come here
you have a friend, very lucky

**Comment by eps696** [comment]
thanxxx, glad to hear ::]
