### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 60.00 MiB (GPU 0; 6.00 GiB total capacity; 4.11 GiB already allocated; 34.82 MiB free; 4.42 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by Dominien** [eps696/aphantasia#22]
i think i have to reduce the batch size but downt know how.

**Comment by eps696** [comment]
it's called `samples` here.

**Comment by Dominien** [comment]
Thank you finally it works, very cool project btw :D

**Comment by eps696** [comment]
glad to hear, enjoy ::]
there will be more additions within coming months - mostly same functionality with other generators (i.e. diff look), maybe smth extra, let's see
