### ISSUE TITLE
Pytorch Import torch.irfft Update to torch.fft.irfft

### ISSUE THREAD

**Issue by CerebralSeed** [eps696/aphantasia#23]
You may need to update your function call as below:

`clip_fft.py:137: UserWarning: The function torch.irfft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.ifft or torch.fft.irfft. (Triggered internally at  /pytorch/aten/src/ATen/native/SpectralOps.cpp:`

**Comment by eps696** [comment]
you may need to update your pytorch environment. 
the call above is performed only for pytorch < 1.8. for modern versions there's updated one on [line 141](https://github.com/eps696/aphantasia/blob/0850b23a5f3e59a293e3ec46df6651b5e0202f24/clip_fft.py#L141).
