### ISSUE TITLE
Specify GPU

### ISSUE THREAD

**Issue by CerebralSeed** [eps696/aphantasia#24]
Could something be added to specify the GPU to use?

**Comment by eps696** [comment]
CUDA_VISIBLE_DEVICES environment variable perfectly controls this. 
you can set it from command line: `set CUDA_VISIBLE_DEVICES=0`
or from python itself:
```
import os
os.environ['CUDA_VISIBLE_DEVICES']='0'
```

**Comment by CerebralSeed** [comment]
Okay, got it. I will give that a try.
