### ISSUE TITLE
DeepSpeed integration for training on local cheaper GPUs.

### ISSUE THREAD

**Issue by Vbansal21** [eps696/aphantasia#25]
This is an awesome repository that you've made.
It would be helpful if you'd integrate DeepSpeed for ZeRO-Infinity NVME offload, for beginners like me😅, as Im only having a 1660ti for training, and trying to generate Full HD images for my PPTs.

**Comment by eps696** [comment]
thank you, glad to hear you liked it.
alas, i've got zero experience with deepspeed yet, so can't help with it. 
i'll leave this issue open, in the hope it happens one day.

have to add tho, this method is not memory-hungry like fat GANs which are mostly used elsewhere, so it should work as it is with any cuda-enabled GPU. i used it on laptop with 1060 mobile (definitely cheaper than 1660ti). just decrease `samples` parameter (kinda batchcount), and there you go.

**Comment by Vbansal21** [comment]
> have to add tho, this method is not memory-hungry like fat GANs which are mostly used elsewhere, so it should work as it is with any cuda-enabled GPU. 
Thanks for your response.
Yeah, the FFT method is quite fast, although the VQGAN method is quite better, but is memory hungry for larger dimensions.  That's where the DeepSpeed would be required.

**Comment by eps696** [comment]
i do not think i'd invest more time in VQGAN methods: there are tons of various flavours for it on the internet. i've put my own implementation here just for collection, no further development is planned for it.
