### ISSUE TITLE
Illustrip3D - problems with video output quality

### ISSUE THREAD

**Issue by Kinkibit** [eps696/aphantasia#29]
Hi Vadim! 

IllusTrip3d is an outstanding tool! Great! Unfortunately, the video generated directly by the Colab notebook is very pixelated and of poor quality. When I stitch the JPGs myself in a video editor, I have jumps and dropouts in between (it also seems to lack 3D depth processing). How and where can I change the values in the notebook so that I have a decent HD output of the video? Thanks in advance for an answer! 

All the best!
Patrick

**Comment by Kinkibit** [comment]
The dropouts were actually due to the video editor. With ffmpeg the conversion to a high quality video worked wonderfully. This is exactly how I imagined it. Thanks for the help!

**Comment by eps696** [comment]
i changed fast video conversion to the slower one, with nearly lossless quality. 
i'm closing the issue for now, please reopen if needed.
