### ISSUE TITLE
Recent change broke Aphantasia.ipynb

### ISSUE THREAD

**Issue by russelldc** [eps696/aphantasia#3]
This (accidental?) change has caused the notebook to run into blocking errors regarding the existence of the `aphantasia/_out/ttt` directory.

https://github.com/eps696/aphantasia/commit/7328c0016a2e6b0e5c394dff1c743f4fb1a4d514#diff-5e754e4f0c2e9323a4a4c199581e6396efc5b7af4165acc368c97bd8401ecb23R216

**Comment by russelldc** [comment]
That's easily fixed by removing the `$` before `tempDir` of course, but now I'm hitting another error I was unable to solve, related to resuming a checkpoint.

At the "Generate" cell of the notebook, it immediately hits this error when I've tried loading any .pt files, which had just been output by the same notebook:
```
AttributeError: ‘bytes’ object has no attribute ‘cuda’
```

at this line inside `clip_fft.py`:
```
spectrum_real_imag_t = resume.cuda().requires_grad_(True)
```

**Comment by eps696** [comment]
first confirmed, that was a bug (my logical mistake), should be fixed now
second will investigate a bit later (tbh never tested resuming with colab myself yet)

**Comment by eps696** [comment]
@russelldc resuming should be fixed by now, so closing the issue. feel free to reopen, if the problem persists.
