### ISSUE TITLE
Can't generate video

### ISSUE THREAD

**Issue by BananaBotYT** [eps696/aphantasia#30]
When it finishes, now it asks for some text in a text box, but I have no clue what it's asking me for. Please help.

**Comment by eps696** [comment]
please **always** provide full text of the error message, or the output of the system. unfortunately, i am not a telepath, and have very little idea what you mean by "some text".

**Comment by BananaBotYT** [comment]
There is no error, just a text box under where it says `.. generating video ..`
I can enter text in and no matter what I type nothing happens except for this message appearing after I hit enter:

`Enter command: <target>|all <time>|-1 <command>[ <argument>]

Parse error, at least 3 arguments were expected'`

**Comment by eps696** [comment]
did you try following the instruction below "If video is not auto-downloaded after generation.."?

**Comment by BananaBotYT** [comment]
I don't see that anywhere on the page.

![image](https://user-images.githubusercontent.com/51053300/142707887-04a2f231-7d4e-4b34-8839-ff19d137d56b.png)

**Comment by eps696** [comment]
![image](https://user-images.githubusercontent.com/4808408/142709960-c8b7796d-1618-4e22-9dbb-545f5dbcc86c.png)
at the bottom of the page.
are we talking about illustrip colab btw?

**Comment by BananaBotYT** [comment]
I don't see that anywhere, my guy. Where is it/How can I get it?

**Comment by eps696** [comment]
what script/page/colab are you talking about then?

**Comment by BananaBotYT** [comment]
> what script/page/colab are you talking about then?

https://colab.research.google.com/github/eps696/aphantasia/blob/master/Aphantasia.ipynb?pli=1&authuser=3#scrollTo=Nq0wA-wc-P-s

**Comment by eps696** [comment]
i cannot reproduce it here. everything has operated normally on my side. 
please log the **complete** info about your problem, including all parameters which you changed, the gpu type from colab and the browser which you use.

**Comment by BananaBotYT** [comment]
I just did another test, changed no settings.

`text: Tomorrow

style: realistic photo`

The text box didn't come up this time, and there was no video.

**Comment by eps696** [comment]
could you please answer my questions, if you want me to solve this problem? 
asking again - which browser are you using?

**Comment by BananaBotYT** [comment]
Opera GX

**Comment by BananaBotYT** [comment]
fixed now, idk what happened.

**Comment by eps696** [comment]
ok, nice to hear. 
as you might see on the github log, i didn't change anything during this discussion, so the issue was kind of glitch, probably with network or browser. i strongly recommend using chrome to work with colab.

for the future, i would greatly appreciate remembering hard rule of logging the issues - provide as much information as possible, to reproduce the issue on the source side. until it's reproduced, it's impossible to tell anything about the cause - let alone to fix it.
