### ISSUE TITLE
Colab notebook "How to just use Aphantasia"

### ISSUE THREAD

**Issue by vsemecky** [eps696/aphantasia#33]
Although this repository contains several colab notebooks, they are all too complex and cluttered. Wouldn't it be possible to make a simple sample notebook that just installs and runs Aphantasia? Without tons of code and complicated colab forms?

I've tried to create such a notebook...

```
!git clone https://github.com/eps696/aphantasia.git /content/aphantasia
%cd /content/aphantasia
!pip -q install -r requirements.txt
!pip install git+https://github.com/openai/CLIP.git
...
...
!python clip_fft.py -t "some text" --size 1280-720
```

...but it always ends up with a `cannot connect to X server` error. Of course the X-server doesn't run in Colab. Wouldn't it be possible to make a simplified, purely command line, version that doesn't need the X-server?

**Comment by eps696** [comment]
`--verbose False` disables cv2 preview in clip_fft.py. 
re: other questions/requests:
1] would you please decide first, what you need - colab of command line. these are different beasts, with different approaches and sets of corresponding features. 
2] "without tons of code" - pardon me??? do you expect it also work somehow?

**Comment by vsemecky** [comment]
ad 1) I need to clone your repo in colab and than just run it as a single command, e.g. `!python clip_fft.py -t "some text" --size 1280-720`

ad 2) I mean "without tons of code" in the notebook. I expect it work due to code in the repo itself.

**Comment by eps696** [comment]
pull request from @dribnet has just been merged. this repo is pip-installable now, and the issue with `--verbose False` [which didn't work, as i expected earlier] should be fixed as well. 
i believe this issue is sorted out now as well, thus closing it now. feel free to reopen it, if not.
