### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Screeauk** [eps696/aphantasia#35]
Hello, trying to run the code but i get an error, how do i solve it ?Thanks!

NameError                                 Traceback (most recent call last)
<ipython-input-2-d675c8122c6f> in <module>()
      2 
      3 get_ipython().system('rm -rf $tempdir')
----> 4 os.makedirs(tempdir, exist_ok=True)
      5 
      6 sideX = 900 #@param {type:"integer"}

NameError: name 'tempdir' is not defined

**Comment by eps696** [comment]
first of all, which code you run?

**Comment by Screeauk** [comment]
I managed to solve it myself, I was reviewing your lecture with CG EVENT 2020 and didn't see that you have to run the code at all stages. Thanks !
