### ISSUE TITLE
Something changed since 04/19/2022

### ISSUE THREAD

**Issue by iamscifi** [eps696/aphantasia#41]
Now it won't create the video, & I get this on the Colab:

.. generating video ..
_out/invisible_man_behind_the_1%_curtain-Film_noir/%04d.jpg: No such file or directory
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-4-0fc2105c4f36>](https://localhost:8080/#) in <module>()
    209   _ = pbar.upd()
    210 
--> 211 HTML(makevid(tempdir))
    212 torch.save(params, tempdir + '.pt')
    213 files.download(tempdir + '.pt')

[<ipython-input-1-8cccf07fd346>](https://localhost:8080/#) in makevid(seq_dir, size)
     67   get_ipython().system('ffmpeg -y -v warning -i $out_sequence -crf 20 $out_video')
     68   # moviepy.editor.ImageSequenceClip(img_list(seq_dir), fps=25).write_videofile(out_video, verbose=False)
---> 69   data_url = "data:video/mp4;base64," + b64encode(open(out_video,'rb').read()).decode()
     70   wh = '' if size is None else 'width=%d height=%d' % (size, size)
     71   return """<video %s controls><source src="%s" type="video/mp4"></video>""" % (wh, data_url)

FileNotFoundError: [Errno 2] No such file or directory: '_out/invisible_man_behind_the_1%_curtain-Film_noir.mp4'

**Comment by eps696** [comment]
just don't use special characters in the promt. 
as you may see from the very error message - `%` sign is treated as a file mask pattern for `ffmpeg` command, hence it breaks the process. without it everything works fine.
[i put handling of such characters in the todo list, but cannot set any expectations time-wise]
