### ISSUE TITLE
Incorporating the -notext option into IllusTrip3D.ipynb

### ISSUE THREAD

**Issue by fr-og** [eps696/aphantasia#42]
Love this implementation greatly!  I was wondering if it would be possible to incorporate the -notext option into the IllusTrip3D.ipynb notebook.

**Comment by eps696** [comment]
thanks for your appreciation! 
on my experience, `--notext` worked somehow [sometimes] with short prompts, but didn't bring any noticeable improvements for longer text strings, which is way more common use case of multi-prompt tools like illustrip. therefore i left that option in the original aphantasia code mostly for historical consistency, not really using it.
i plan to extend prompts management though - to the current "industry-standard" syntax with weights, like `goodprompt1:1 | goodprompt2:1 | badprompt:-0.5`. this would give more flexible control over the result, allowing to cleanup specific pieces from unwanted output [including those "graffiti"] - in my experience, that's more promising approach.

**Comment by eps696** [comment]
text prompts parsing is finally in place, both for aphantasia [still] and illustrip [motion], local and colabs. 
`--notext` option therefore is eliminated everywhere, as it hardly compatible with multiple weighted prompts.
considering this issue as closed now.
