### ISSUE TITLE
[Feature] Non-Random Slices for Locational Encoding of Input Image

### ISSUE THREAD

**Issue by torridgristle** [eps696/aphantasia#6]
Rather than doing multiple random slices of the input image to match using CLIP, what if it was an orderly grid covering the image? Such that each chunk of an image can be encoded and stored in an array, and later when encoding the output image to compare to the input image it can follow the same orderly grid and compare to entries in the array, with the intent of comparing the same locations of the images. I imagine some overlap in the slices would be required.

I reckon that with this, if CLIP detects a feature in a certain place, Aphantasia will try to match that same feature in that same place, instead of trying to match the overall description of an image.

**Comment by eps696** [comment]
i used exactly that trick in another colab - [CLIP+SIREN](https://colab.research.google.com/drive/1L14q4To5rMK8q2E6whOibQBnPnVbRJ_7), `sync_cut` option. 
if you look at the code of this repo, you'll notice it also has some legacy of that: 
- [`slice_imgs`](https://github.com/eps696/aphantasia/blob/6a26d8fb3b3c40e3d9de5f75c47c084723459416/clip_fft.py#L148) takes list of images as input, to process them in such sync, 
- [sliced result](https://github.com/eps696/aphantasia/blob/6a26d8fb3b3c40e3d9de5f75c47c084723459416/clip_fft.py#L195) is addressed by index [-1] (input was addressed as [0]), etc.

alas, it didn't work well enough with FFT, therefore SSIM loss has been used instead.
